// <auto-generated />
using System;
using ASP.NET_Uni_Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NETUniProject.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230116115535_Version3_0")]
    partial class Version30
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NET_Uni_Project.Models.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Buyout")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("buyout");

                    b.Property<DateTime>("CloseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("closeDate");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CurrentBid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("StartingBid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("startingBid");

                    b.Property<string>("Winner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WinningBid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("winningBid");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("ASP.NET_Uni_Project.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("GameSerieId")
                        .HasColumnType("int");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Release")
                        .HasColumnType("datetime2")
                        .HasColumnName("release");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("GameSerieId");

                    b.HasIndex("ProducerId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Part 3 of Geralts epic journey!",
                            GameSerieId = 3,
                            ProducerId = 1,
                            Release = new DateTime(2015, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Long awaited sequel",
                            GameSerieId = 1,
                            ProducerId = 2,
                            Release = new DateTime(1998, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fallout 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "First part in the series to use first person perspective.",
                            GameSerieId = 1,
                            ProducerId = 3,
                            Release = new DateTime(2008, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fallout 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Create your favourite football team.",
                            GameSerieId = 2,
                            ProducerId = 4,
                            Release = new DateTime(2008, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fifa 09"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Collect all your favourite players in the new FUT mode!",
                            GameSerieId = 2,
                            ProducerId = 4,
                            Release = new DateTime(2020, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fifa 21"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Space exploration/FPS made by the creators of Fallout",
                            GameSerieId = 4,
                            ProducerId = 2,
                            Release = new DateTime(2019, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Outer Worlds"
                        });
                });

            modelBuilder.Entity("ASP.NET_Uni_Project.Models.GameSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("genre");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("GameSeries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A postapocalyptic future roleplaying game.",
                            Genre = "RPG",
                            Name = "Fallout"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Multiplayer football simulator.",
                            Genre = "Sport",
                            Name = "Fifa"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Based on the books of Andrzej Sapkowski",
                            Genre = "RPG",
                            Name = "The Witcher"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Space first person shooter.",
                            Genre = "FPS",
                            Name = "The Outer Worlds"
                        });
                });

            modelBuilder.Entity("ASP.NET_Uni_Project.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("datetime2")
                        .HasColumnName("founded");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Producers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Polish producer.",
                            Founded = new DateTime(2000, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CD Projekt RED"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Makes RPG games.",
                            Founded = new DateTime(1994, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Obsidian"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Great buggy games",
                            Founded = new DateTime(2009, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bethesda"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Making fat stacks of cash.",
                            Founded = new DateTime(2005, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Electronic Arts"
                        });
                });

            modelBuilder.Entity("ASP.NET_Uni_Project.Models.Auction", b =>
                {
                    b.HasOne("ASP.NET_Uni_Project.Models.Game", "Game")
                        .WithMany("Auctions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ASP.NET_Uni_Project.Models.Game", b =>
                {
                    b.HasOne("ASP.NET_Uni_Project.Models.GameSerie", "GameSerie")
                        .WithMany("Games")
                        .HasForeignKey("GameSerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NET_Uni_Project.Models.Producer", "Producer")
                        .WithMany("Games")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSerie");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("ASP.NET_Uni_Project.Models.Game", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("ASP.NET_Uni_Project.Models.GameSerie", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("ASP.NET_Uni_Project.Models.Producer", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
